### ISSUE TITLE
npm install now on Lion

### ISSUE THREAD

**Issue by henryoswald** [Flotype/now#123]
'npm install now' is throwing errors on my laptop but not my desktop, the one thing that changed is I upgraded the laptop to lion a couple of days ago. 

0.7.2

```
npm ERR! error installing node-proxy@0.4.0 Error: node-proxy@0.4.0 install: `make`
npm ERR! error installing node-proxy@0.4.0 `sh "-c" "make"` failed with 127
npm ERR! error installing node-proxy@0.4.0     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing node-proxy@0.4.0     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing node-proxy@0.4.0     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! error installing now@0.7.2 Error: node-proxy@0.4.0 install: `make`
npm ERR! error installing now@0.7.2 `sh "-c" "make"` failed with 127
npm ERR! error installing now@0.7.2     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing now@0.7.2     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing now@0.7.2     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! node-proxy@0.4.0 install: `make`
npm ERR! `sh "-c" "make"` failed with 127
npm ERR! 
npm ERR! Failed at the node-proxy@0.4.0 install script.
npm ERR! This is most likely a problem with the node-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-proxy
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "now"
npm ERR! cwd /Users/henry/Desktop/a
npm ERR! node -v v0.4.6
npm ERR! npm -v 1.0.22
```

same on 0.6.1:

```
    npm ERR! error installing node-proxy@0.3.2 Error: node-proxy@0.3.2 install: `make`
    npm ERR! error installing node-proxy@0.3.2 `sh "-c" "make"` failed with 127
    npm ERR! error installing node-proxy@0.3.2     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
    npm ERR! error installing node-proxy@0.3.2     at ChildProcess.emit (events.js:67:17)
    npm ERR! error installing node-proxy@0.3.2     at ChildProcess.onexit (child_process.js:192:12)
    npm ERR! error installing now@0.6.1 Error: node-proxy@0.3.2 install: `make`
    npm ERR! error installing now@0.6.1 `sh "-c" "make"` failed with 127
    npm ERR! error installing now@0.6.1     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
    npm ERR! error installing now@0.6.1     at ChildProcess.emit (events.js:67:17)
    npm ERR! error installing now@0.6.1     at ChildProcess.onexit (child_process.js:192:12)
```

**Comment by ruiiiijiiiiang** [comment]
Have you tried `npm install now -g`?

**Comment by ericz** [comment]
Hi @henryoswald

Is there additional debug output from npm above the beginning line you've copied?

**Comment by henryoswald** [comment]
ok well that was silly. Turns out installing Lion removes XCode and everything that comes with it including Make....  didn't even think of checking make until I tried to do use it else where.
