### ISSUE TITLE
TypeError: Object #<Object> has no method 'renderFile'

### ISSUE THREAD

**Issue by dresende** [Flotype/now#135]
```

{ stack: [Getter/Setter],
  arguments: 
   [ 'renderFile',
     { version: '0.15.4',
       cache: {},
       selfClosing: [Object],
       doctypes: [Object],
       filters: [Object],
       utils: [Object],
       Compiler: [Function: Compiler],
       Parser: [Object],
       nodes: [Object],
       runtime: [Object],
       compile: [Function] } ],
  type: 'undefined_method',
  message: [Getter/Setter] }
TypeError: Object #<Object> has no method 'renderFile'
    at Server.<anonymous> (...)
    at Server.<anonymous> (/usr/local/lib/node/.npm/now/0.7.4/package/lib/fileServer.js:38:31)
    at Manager.handleRequest (/usr/local/lib/node/.npm/socket.io/0.7.9/package/lib/manager.js:511:28)
    at Server.<anonymous> (/usr/local/lib/node/.npm/socket.io/0.7.9/package/lib/manager.js:96:10)
    at Server.emit (events.js:67:17)
    at HTTPParser.onIncoming (http.js:1134:12)
    at HTTPParser.onHeadersComplete (http.js:108:31)
    at Socket.ondata (http.js:1029:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```
- node v0.4.11
- socket.io 0.8.4 (but you can see that now seems to be using 0.7.9.. how?)
- now 0.7.4

**Comment by dresende** [comment]
Sorry, found the problem. Not now, it's jade problem :)
