### ISSUE TITLE
Object.keys called on non-object

### ISSUE THREAD

**Issue by mikl** [Flotype/now#142]
I keep getting this traceback when running my app:

```
{ stack: [Getter/Setter],
  arguments: [ 'keys' ],
  type: 'obj_ctor_property_non_object',
  message: [Getter/Setter] }
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at [object Object].<anonymous> (/Users/mikl/[...]/node_modules/now/lib/group.js:61:21)
    at Socket.rfcHandler (/Users/mikl/[...]/node_modules/now/lib/user.js:92:19)
    at Socket.$emit (events.js:64:17)
    at SocketNamespace.handlePacket (/Users/mikl/[...]/node_modules/now/node_modules/socket.io/lib/namespace.js:331:20)
    at Manager.onClientMessage (/Users/mikl/[...]/node_modules/now/node_modules/socket.io/lib/manager.js:436:38)
    at WebSocket.onMessage (/Users/mikl/[...]/node_modules/now/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/Users/mikl/[...]/node_modules/now/node_modules/socket.io/lib/transports/websocket/default.js:37:10)
    at Parser.emit (events.js:64:17)
    at Parser.parse (/Users/mikl/[...]/node_modules/now/node_modules/socket.io/lib/transports/websocket/default.js:331:12)
```

I have no idea what's causing this, but it started showing after upgrading to 0.7.5… (I think we were on 0.6.x before)

**Comment by ericz** [comment]
Hi mikl,

Could you send some code that will trigger this error?

**Comment by mikl** [comment]
My colleague and I have spent hours poring over the code, and we can't figure out what triggers this error, but the code runs just fine on Now 0.6.1. Is there something that changed in 0.7 related to groups that might cause this?

**Comment by steveWang** [comment]
It has to do with `group.count(cb)`, evidently. (posted to facilitate finding code that replicates this behavior)

Stack trace seems to indicate that `group.users` isn't being initialized. How this might happen, I have no idea.

**Comment by ericz** [comment]
I'm taking a look into this

On Sat, Sep 24, 2011 at 8:49 AM, Steve Wang <
reply@reply.github.com>wrote:

> It has to do with `group.count(cb)`, evidently. (posted to facilitate
> finding code that replicates this behavior)
> 
> Stack trace seems to indicate that `group.users` isn't being initialized.
> How this might happen, I have no idea.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Flotype/now/issues/142#issuecomment-2186910

## 

510-691-3951
EECS Student at UC Berkeley
http://ericzhang.com

**Comment by ericz** [comment]
Hi mikl,

I can't figure out how to reproduce it. If you have any hints on how this could be triggered that would be extremely appreciated.

Eric

**Comment by andrecaribe** [comment]
I got this error too. @steveWang is correct, happens when we use for example`nowjs.getGroup(this.now.room).now.receiveMessage('SERVER', this.now.name);` and `this.now.room` was not initialized.

**Comment by dachev** [comment]
I'm getting this error too. It only happens with cross domain connections. now.ready on the client executes as though everything is fine, but the server prints this error. Subsequent calls to any server functions fail silently.

**Comment by dachev** [comment]
In my case data in user.js:98 is a string: [{"now.pingReceiver": {"fqn": "now.pingReceiver"}, "now.clockStateChanged": {"fqn": "now.clockStateChanged"}}]

**Comment by dachev** [comment]
When the error occurs "params" in socket.io's namespace.js:335 looks like this:
    [ 'rv', '[{"now.pingReceiver": {"fqn": "now.pingReceiver"}, "now.clockStateChanged": {"fqn": "now.clockStateChanged"}}]' ]

Notice the second element is a string.

A successful call looks like this:
    [ 'rfc', { fqn: 'now.pong', args: [ 1329800562706 ] } ]

**Comment by dachev** [comment]
After further investigation it turned out the problem was caused by the presence of prototype.js on the client.

**Comment by steveWang** [comment]
Ah yes, Socket.IO doesn't play well with Prototype.js overriding Array.prototype.toJSON (which completely disregards MDN spec). :)

To elaborate: we encountered this some time over the summer, but there really wasn't anything we could do about it -- MDN spec says that obj.toJSON should return the equivalent object (so, for instance, if you have an object masquerading as an array, its toJSON should return an array if you want JSON.stringify to serialize it correctly). However, Prototype.js decided that it would return a JSON.stringified version of said array, instead. Naturally, this breaks serializing.

We could always have a hack on our end to delete Array.prototype.toJSON if Prototype.js is active, but it'd be just that: a hack.

This is why extending default constructor prototypes is generally a bad idea. Spec could get updated without you noticing, and all of a sudden your implementation goes from being useful to being flat-out wrong and harmful.
