### ISSUE TITLE
EventEmitter memory leak detected - when using RedisStore

### ISSUE THREAD

**Issue by alessioalex** [Flotype/now#147]
→ node server.js 
   info  - socket.io started
Server started on port 8080
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at RedisClient.<anonymous> (events.js:126:17)
    at RedisClient.subscribe (/var/www/node_apps/chat/node_modules/socket.io/lib/stores/redis.js:132:18)
    at RedisClient.emit (events.js:81:20)
    at RedisClient.return_reply (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/index.js:450:22)
    at RedisReplyParser.<anonymous> (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/index.js:81:14)
    at RedisReplyParser.emit (events.js:64:17)
    at RedisReplyParser.add_multi_bulk_reply (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:311:14)
    at RedisReplyParser.send_reply (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:274:18)
    at RedisReplyParser.execute (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:114:22)
    at RedisClient.on_data (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/index.js:358:27)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at Redis.<anonymous> (events.js:126:17)
    at RedisClient.subscribe (/var/www/node_apps/chat/node_modules/socket.io/lib/stores/redis.js:134:14)
    at RedisClient.emit (events.js:81:20)
    at RedisClient.return_reply (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/index.js:450:22)
    at RedisReplyParser.<anonymous> (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/index.js:81:14)
    at RedisReplyParser.emit (events.js:64:17)
    at RedisReplyParser.add_multi_bulk_reply (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:311:14)
    at RedisReplyParser.send_reply (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:274:18)
    at RedisReplyParser.execute (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:114:22)
    at RedisClient.on_data (/var/www/node_apps/chat/node_modules/socket.io/node_modules/redis/index.js:358:27)

**Comment by alessioalex** [comment]
oups, wrong github page :)))
