### ISSUE TITLE
Install errors and I am new at this

### ISSUE THREAD

**Issue by successcoach** [Flotype/now#158]
```npm install now -g
npm WARN node-proxy@0.5.2 package.json: bugs['web'] should probably be bugs['url']

> node-proxy@0.5.2 install /usr/local/lib/node_modules/now/node_modules/node-proxy
> make

BUILDING: C++ Component
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.046s)
Waf: Entering directory `/usr/local/lib/node_modules/now/node_modules/node-proxy/src/build'
[1/2] cxx: node-proxy.cc -> build/Release/node-proxy_1.o
[2/2] cxx_link: build/Release/node-proxy_1.o -> build/Release/node-proxy.node
npm ERR! Failed unpacking /tmp/npm-1322648053217/1322648053217-0.7195738274604082/tmp.tgz
npm ERR! couldn't unpack /tmp/npm-1322648053217/1322648053217-0.7195738274604082/tmp.tgz to /tmp/npm-1322648053217/1322648053217-0.7195738274604082/contents
npm ERR! error installing socket.io-client@0.8.7 Error:`tar "-zmvxpf" "/tmp/npm-1322648053217/1322648053217-0.7195738274604082/tmp.tgz" "-o"`
npm ERR! error installing socket.io-client@0.8.7 failed with 2
npm ERR! error installing socket.io-client@0.8.7     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:217:20)
npm ERR! error installing socket.io-client@0.8.7     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing socket.io-client@0.8.7     at maybeExit (child_process.js:359:16)
npm ERR! error installing socket.io-client@0.8.7     at Process.onexit (child_process.js:395:5)
npm ERR! error installing socket.io@0.8.7 Error:`tar "-zmvxpf" "/tmp/npm-1322648053217/1322648053217-0.7195738274604082/tmp.tgz" "-o"`
npm ERR! error installing socket.io@0.8.7 failed with 2
npm ERR! error installing socket.io@0.8.7     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:217:20)
npm ERR! error installing socket.io@0.8.7     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing socket.io@0.8.7     at maybeExit (child_process.js:359:16)
npm ERR! error installing socket.io@0.8.7     at Process.onexit (child_process.js:395:5)
npm ERR! error installing now@0.7.6 Error:`tar "-zmvxpf" "/tmp/npm-1322648053217/1322648053217-0.7195738274604082/tmp.tgz" "-o"`
npm ERR! error installing now@0.7.6 failed with 2
npm ERR! error installing now@0.7.6     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:217:20)
npm ERR! error installing now@0.7.6     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing now@0.7.6     at maybeExit (child_process.js:359:16)
npm ERR! error installing now@0.7.6     at Process.onexit (child_process.js:395:5)
npm ERR! Error:`tar "-zmvxpf" "/tmp/npm-1322648053217/1322648053217-0.7195738274604082/tmp.tgz" "-o"`
npm ERR! failed with 2
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:217:20)
npm ERR!     at ChildProcess.emit (events.js:70:17)
npm ERR!     at maybeExit (child_process.js:359:16)
npm ERR!     at Process.onexit (child_process.js:395:5)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 2.6.18-194.32.1.el5
npm ERR! command "node" "/usr/local/bin/npm" "install" "now" "-g"
npm ERR! cwd /var/www/vhosts/mymaptowellness.com/httpdocs
npm ERR! node -v v0.6.1
npm ERR! npm -v 1.0.106
collect2: ld returned 1 exit status
Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 16, in ?
    Scripting.prepare(t, os.getcwd(), VERSION, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 145, in prepare
    prepare_impl(t, cwd, ver, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 135, in prepare_impl
    main()
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 188, in main
    fun(ctx)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 386, in build
    return build_impl(bld)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 408, in build_impl
    info("Waf: Leaving directory`%s'" % bld.bldnode.abspath())
  File "/usr/local/bin/../lib/node/wafadmin/Node.py", line 420, in abspath
    ret = self.**class**.bld.cache_node_abspath[variant].get(self.id, None)
AttributeError: 'NoneType' object has no attribute 'cache_node_abspath'
/bin/sh: line 0: cd: ..: No such file or directory
make: **\* [all] Error 1
npm ERR! error installing node-proxy@0.5.2 Error: node-proxy@0.5.2 install: `make`
npm ERR! error installing node-proxy@0.5.2 `sh "-c" "make"` failed with 2
npm ERR! error installing node-proxy@0.5.2     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing node-proxy@0.5.2     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing node-proxy@0.5.2     at maybeExit (child_process.js:359:16)
npm ERR! error installing node-proxy@0.5.2     at Process.onexit (child_process.js:395:5)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/vhosts/mymaptowellness.com/httpdocs/npm-debug.log
npm not ok```

**Comment by yuchi** [comment]
Actually this is not a problem with _now_ but with _node-proxy_ (which is a module that implements the awesome [Harmony Proxies](http://wiki.ecmascript.org/doku.php?id=harmony:proxies) in node.js).

Probably you have problems with node-waf. What's your environment?

Addendum: would you mind to edit your issue with triple-backticks before end after the log?

**Comment by successcoach** [comment]
Thanks for the pointers and help as you can see my environment from http://mymaptowellness.com/phpinfo.php and I will edit log with triple backticks.

John

**Comment by vicary** [comment]
Kindly refer this to a node-proxy issue, the author doesn't recommend an alternative proxy on windows environment, but it seems to be out soon.

[node-proxy issue #19](https://github.com/samshull/node-proxy/issues/19)

**Comment by ericz** [comment]
Closing. Feel free to reopen if issue persists. Or email team@nowjs.com
