### ISSUE TITLE
Server not starting b/c of node-proxy: FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed

### ISSUE THREAD

**Issue by stphnthiel** [Flotype/now#186]
Hi all,

when I try to run my server with Nowjs (using express) node js fails to start because of the node-proxy dependency:

this is the message when running on the mac:

```
FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed
```

this is the message when running on ubuntu:

```
[Error: Unable to load shared library /home/flowmill/server/flowmill/node_modules/now/node_modules/node-proxy/lib/node-proxy.node]
Error: Unable to load shared library /home/flowmill/server/flowmill/node_modules/now/node_modules/node-proxy/lib/node-proxy.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/flowmill/server/flowmill/node_modules/now/lib/proxy.js:10:13)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
```

my module config is the same on both machines: this is npm list:

```
├─┬ express@2.5.8 
│ ├─┬ connect@1.8.6 
│ │ └── formidable@1.0.9 
│ ├── mime@1.2.4 
│ ├── mkdirp@0.3.0 
│ └── qs@0.4.2 
├─┬ mail@0.2.3 
│ └── reparse@0.1.2 
├─┬ mongodb@0.9.9-7 
│ └── bson@0.0.4 
├─┬ mongoose@2.5.11 
│ ├── hooks@0.2.0 
│ └── mongodb@0.9.9-5 
└─┬ now@0.8.1 
  ├── node-proxy@0.5.2 
  └─┬ socket.io@0.9.2 
    ├── policyfile@0.0.4 
    ├── redis@0.6.7 
    └─┬ socket.io-client@0.9.2 
      ├─┬ active-x-obfuscator@0.0.1 
      │ └── zeparser@0.0.5 
      ├── uglify-js@1.2.5 
      ├─┬ ws@0.4.8 
      │ ├── commander@0.5.0 
      │ └── options@0.0.3 
      └── xmlhttprequest@1.2.2 
```

Any hints on what’s the problem and how I can fix that?

**Comment by stphnthiel** [comment]
thanks in advance for your help!

**Comment by rubemz** [comment]
Any updates regarding this issue? 
I'm facing the same problem.

**Comment by jameskeane** [comment]
Update your version of node.
