### ISSUE TITLE
npm install now ..... throwing error

### ISSUE THREAD

**Issue by lavinachitara** [Flotype/now#211]
Hello,

I am in a big stuff, I am not getting why now package is not installing on my windows machine.

I installed  node version of 0.6.18.

and tried to install now package but got following error on command terminal

C:\Users\user>npm install now
npm http GET https://registry.npmjs.org/now
npm http 304 https://registry.npmjs.org/now
npm http GET https://registry.npmjs.org/node-proxy
npm http GET https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/node-proxy
npm http 304 https://registry.npmjs.org/socket.io

> node-proxy@0.6.0 install C:\Users\user\AppData\Roaming\npm\node_modules\now\no
> de_modules\node-proxy
> node-gyp configure build

C:\Users\user\AppData\Roaming\npm\node_modules\now\node_modules\node-proxy>node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\n
ode-gyp\bin\node-gyp.js" configure build
info it worked if it ends with ok
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/redis/0.7.3
info downloading: http://nodejs.org/dist/v0.6.18/node-v0.6.18.tar.gz
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.11
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/tinycolor
npm http 200 https://registry.npmjs.org/commander

> ws@0.4.23 install C:\Users\user\AppData\Roaming\npm\node_modules\now\node_modu
> les\socket.io\node_modules\socket.io-client\node_modules\ws
> node install.js

[ws v0.4.23] Attempting to compile blazing fast native extensions.
info downloading: http://nodejs.org/dist/v0.6.18/node.lib
info downloading: http://nodejs.org/dist/v0.6.18/x64/node.lib
spawn python [ 'C:\Users\user\.node-gyp\0.6.18\tools\gyp_addon',
  'binding.gyp',
  '-IC:\Users\user\AppData\Roaming\npm\node_modules\now\node_modules\no
de-proxy\build\config.gypi',
  '-f',
  'msvs',
  '-G',
  'msvs_version=2010' ]
spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe [ 'build/binding
.sln',
  '/clp:Verbosity=minimal',
  '/nologo',
  '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets
(42,5): error MSB8020: The builds tools for Visual Studio 2010 (Platform Toolse
t = 'v100') cannot be found. To build using the v100 build tools, either click
the Project menu or right-click the solution, and then select "Update VC++ Proj
ects...". Install Visual Studio 2010 to build using the Visual Studio 2010 buil
d tools. [C:\Users\user\AppData\Roaming\npm\node_modules\now\node_modules\node-
proxy\build\nodeproxy.vcxproj]
ERR! Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed w
ith exit code: 1
    at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_module
s\node-gyp\lib\build.js:209:23)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:362:16)
    at Process.onexit (child_process.js:398:5)
ERR! not ok
[ws v0.4.23] Native code compile failed (but the module will still work):
[ws v0.4.23] The native extensions are faster, but not required.
[ws v0.4.23] On Windows, native extensions require Visual Studio and Python.
[ws v0.4.23] On Unix, native extensions require Python, make and a C++ compiler.

[ws v0.4.23] Start npm with --ws:verbose to show compilation output (if any).

npm ERR! node-proxy@0.6.0 install: `node-gyp configure build`
npm ERR! `cmd "/c" "node-gyp configure build"` failed with 1
npm ERR!
npm ERR! Failed at the node-proxy@0.6.0 install script.
npm ERR! This is most likely a problem with the node-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-proxy
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "now"
npm ERR! cwd C:\Users\user
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.21
npm ERR! code ELIFECYCLE
npm ERR! message node-proxy@0.6.0 install: `node-gyp configure build`
npm ERR! message `cmd "/c" "node-gyp configure build"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\user\npm-debug.log
npm not ok

I checked in log also : C:\Users\user\npm-debug.log

info install socket.io-client@0.9.11
info postinstall socket.io-client@0.9.11
verbose about to build C:\Users\user\AppData\Roaming\npm\node_modules\now\node_modules\socket.io
info build C:\Users\user\AppData\Roaming\npm\node_modules\now\node_modules\socket.io
verbose from cache C:\Users\user\AppData\Roaming\npm\node_modules\now\node_modules\socket.io\package.json
verbose linkStuff [ true,
verbose linkStuff   'C:\Users\user\AppData\Roaming\npm\node_modules',
verbose linkStuff   false,
verbose linkStuff   'C:\Users\user\AppData\Roaming\npm\node_modules\now\node_modules' ]
info linkStuff socket.io@0.9.11
verbose linkBins socket.io@0.9.11
verbose linkMans socket.io@0.9.11
verbose rebuildBundles socket.io@0.9.11
verbose rebuildBundles [ 'policyfile', 'redis', 'socket.io-client' ]
info install socket.io@0.9.11
info postinstall socket.io@0.9.11
verbose about to build C:\Users\user\AppData\Roaming\npm\node_modules\now
info unbuild C:\Users\user\AppData\Roaming\npm\node_modules\now
verbose from cache C:\Users\user\AppData\Roaming\npm\node_modules\now\package.json
info preuninstall now@0.8.1
info uninstall now@0.8.1
verbose unbuild now@0.8.1 [ true,
verbose unbuild now@0.8.1   'C:\Users\user\AppData\Roaming\npm\node_modules',
verbose unbuild now@0.8.1   'C:\Users\user\AppData\Roaming\npm\node_modules' ]
info postuninstall now@0.8.1
ERR! node-proxy@0.6.0 install: `node-gyp configure build`
ERR! `cmd "/c" "node-gyp configure build"` failed with 1
ERR! 
ERR! Failed at the node-proxy@0.6.0 install script.
ERR! This is most likely a problem with the node-proxy package,
ERR! not with npm itself.
ERR! Tell the author that this fails on your system:
ERR!     node-gyp configure build
ERR! You can get their info via:
ERR!     npm owner ls node-proxy
ERR! There is likely additional logging output above.
ERR! 
ERR! System Windows_NT 6.1.7600
ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "now"
ERR! cwd C:\Users\user
ERR! node -v v0.6.18
ERR! npm -v 1.1.21
ERR! code ELIFECYCLE
ERR! message node-proxy@0.6.0 install: `node-gyp configure build`
ERR! message `cmd "/c" "node-gyp configure build"` failed with 1
ERR! errno {}
verbose exit [ 1, true ]

but couldn't trace that what is the issue.

I tried by below link also but still same issue, couldn't access now module

http://blog.nowjs.com/running-nowjs-natively-on-windows

Please help me, I need to install it on windows server 2008 R2 standard.
Is It possible to install now package on this machine.

Thanks and Regards,
Lavina

**Comment by lavinachitara** [comment]
Yes!!!!! I got solutions for above issue.

I want to share with all guys. Below is the actual steps I followed :
1. Install nodejs from nodejs.org
2. Install Microsoft Visual Studio 2010 Professional edition (Not express edition because I tried by express edition that was not working)
3. Install Python 2.7.3
4. Run npm install now on command prompt

I am so happy to install now package on windows after putting so much efforts. :-)
