### ISSUE TITLE
Client disconnect?

### ISSUE THREAD

**Issue by j03m** [Flotype/now#24]
Hey, I unfortunately don't have a great deal of replication information around this but I did grab the stack trace from Node. I was running the chat demo (which is awesome) and I noticed every once in a while one of the clients would disconnect. It would continue to publish updates, but not receive them (which I found odd). It did occur at the same time as this stack trace:

{ stack: [Getter/Setter],
  arguments: [ 'hasOwnProperty', undefined ],
  type: 'non_object_property_call',
  message: [Getter/Setter] }
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at Object.getVarFromFqn (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowUtil.js:86:18)
    at Object.remoteCall (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowServerLib.js:55:31)
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowServerLib.js:273:48)
    at [object Object].emit (events.js:64:17)
    at [object Object]._onMessage (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/client.js:58:10)
    at Parser.<anonymous> (native)
    at Parser.emit (events.js:64:17)
    at Parser.parse (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:195:12)
    at Parser.add (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:182:8)
    at Socket.<anonymous> (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:116:17)
{ stack: [Getter/Setter],
  arguments: [ 'hasOwnProperty', undefined ],
  type: 'non_object_property_call',
  message: [Getter/Setter] }
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at Object.getVarFromFqn (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowUtil.js:86:18)
    at Object.remoteCall (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowServerLib.js:55:31)
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowServerLib.js:273:48)
    at [object Object].emit (events.js:64:17)
    at [object Object]._onMessage (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/client.js:58:10)
    at Parser.<anonymous> (native)
    at Parser.emit (events.js:64:17)
    at Parser.parse (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:195:12)
    at Parser.add (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:182:8)
    at Socket.<anonymous> (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:116:17)
{ stack: [Getter/Setter],
  arguments: [ 'hasOwnProperty', undefined ],
  type: 'non_object_property_call',
  message: [Getter/Setter] }
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at Object.getVarFromFqn (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowUtil.js:86:18)
    at Object.remoteCall (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowServerLib.js:55:31)
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/now/0.3.1/package/lib/nowServerLib.js:273:48)
    at [object Object].emit (events.js:64:17)
    at [object Object]._onMessage (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/client.js:58:10)
    at Parser.<anonymous> (native)
    at Parser.emit (events.js:64:17)
    at Parser.parse (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:195:12)
    at Parser.add (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:182:8)
    at Socket.<anonymous> (/usr/local/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/websocket.js:116:17)

**Comment by ericz** [comment]
Hmm I will look into this.

Thanks for the report!

**Comment by j03m** [comment]
Not sure if it's related but a new version of Socket.IO came out today,
might possibly help. I will give it a whirl when I get home.

**Comment by ericz** [comment]
Based on the stack trace, this looks like an issue with improper disconnections, specifically when the client times out or otherwise disconnections ungracefully. We'll be fixing this in the next version of now.

**Comment by ericz** [comment]
Closing

**Comment by j03m** [comment]
Awesome, will give it a spin.
